# -*- coding: utf-8 -*-
"""
Created on Mon Apr  5 00:00:30 2021

@author: AsteriskAmpersand
"""
testCases=r"""E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_0050_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\ltc2.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_09_0003_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\S_Swd058_HDR.tex
E:\MHR\MHR_Tex_Chopper\tests\mesh_0004_cm_00_0013_Vnm_MSK3.tex
E:\MHR\MHR_Tex_Chopper\tests\mesh_0004_cm_00_0012_Vnm_MSK3.tex
E:\MHR\MHR_Tex_Chopper\tests\ColorCubeLinear.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_05_0001_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\TexSkyBall_base_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\CharaMake05_ALB.tex
E:\MHR\MHR_Tex_Chopper\tests\BlueNoise16x16.tex
E:\MHR\MHR_Tex_Chopper\tests\m_leg238_CMM.tex
E:\MHR\MHR_Tex_Chopper\tests\BlueNoise.tex
E:\MHR\MHR_Tex_Chopper\tests\NullGray.tex
E:\MHR\MHR_Tex_Chopper\tests\NullATOS.tex
E:\MHR\MHR_Tex_Chopper\tests\em109_00_FVM_MSK3.tex
E:\MHR\MHR_Tex_Chopper\tests\em109_scale_CMM.tex
E:\MHR\MHR_Tex_Chopper\tests\Noise3D_MSK4.tex
E:\MHR\MHR_Tex_Chopper\tests\em001_spine_EMI.tex
E:\MHR\MHR_Tex_Chopper\tests\gm029_000_FX_EMI.tex
E:\MHR\MHR_Tex_Chopper\tests\em102_00_feather_FVM_MSK3.tex
E:\MHR\MHR_Tex_Chopper\tests\otd_tail004_FVM_MSK3.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_08_0004_MSK3.tex
E:\MHR\MHR_Tex_Chopper\tests\S_Axe082_FVM_MSK3.tex
E:\MHR\MHR_Tex_Chopper\tests\m03a07_flowmap00_MSK2.tex
E:\MHR\MHR_Tex_Chopper\tests\NullBlack3D.tex
E:\MHR\MHR_Tex_Chopper\tests\NullWhite.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_2011_ALB.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_ita11_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\pixtest_ALPG.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_kakejiku04_ALB.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_08_0001_ALB.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_kasaya03_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_onigiriya02_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\m03_ki069_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_mi21_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_zabuton00_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_04_0010_ALB.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_tatara01_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\m04_moyou03_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_mi20_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_kusari01_ALB.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_yakisakana_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_zakkayatubo_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_2010_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_onigiriya04_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_kusa13_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\m03_ki73_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\m03_ki72_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_zakkayakomono09_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\S_Axe087_CMM.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_onigiriya01_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\m01_mokuzai05_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tent_naibu12_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\m22_nawa01_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_kusa32_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\Light_test_ALB.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_kusa11_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\SpeedT_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\CAPCOM_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\m02a00_kinkei2_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_miki04_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\cloud80_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\com_kiri01_ALB.tex
E:\MHR\MHR_Tex_Chopper\tests\m_wst201_NRRT.tex
E:\MHR\MHR_Tex_Chopper\tests\eye_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_08_0001_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\m_leg200_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\shader_waterfall_distortion_loopmask_MSK1.tex
E:\MHR\MHR_Tex_Chopper\tests\com_mask03_MSK1.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_nuno09_MSK1.tex
E:\MHR\MHR_Tex_Chopper\tests\f_hair007_Accesories_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\VolumeNoise_LIN.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_kasaya04_MSK1.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_tyoutinmoji08_MSK1.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_nuno09_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\m01_moyou06_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\chijiiwa_pat128_MSK1.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_su03_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\m04_moyou03_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_kusari01_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_nuno03_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\lens_mask.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_kasaya03_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_kusa13_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\m01_kusa34_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_zakkayakomono09_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\S_Axe085_FX.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_mi22_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\m01_eda09_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\m03_ki73_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\m03_ki41_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\m22_sango04_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\eye_OCC.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_064_00_Atlas_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\m02a00_kinkei2_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\m03_ki48_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_kusa06_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\com_kiri01_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\com_su_09_ALP.tex
E:\MHR\MHR_Tex_Chopper\tests\com_flow08_MSK2.tex
E:\MHR\MHR_Tex_Chopper\tests\h01_mizu01_MSK2.tex
E:\MHR\MHR_Tex_Chopper\tests\ems092_clew_FX_EMI.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_a03_mizu01_flow_MSK2.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_flow02_MSK2.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_mizu01_flow_MSK2.tex
E:\MHR\MHR_Tex_Chopper\tests\m03_flow31_MSK2.tex
E:\MHR\MHR_Tex_Chopper\tests\NullBlackCubemap.tex
E:\MHR\MHR_Tex_Chopper\tests\NullLightmap.tex
E:\MHR\MHR_Tex_Chopper\tests\CubeMap_a04_junbi.tex
E:\MHR\MHR_Tex_Chopper\tests\IBL_small.tex
E:\MHR\MHR_Tex_Chopper\tests\cubemap_2.tex
E:\MHR\MHR_Tex_Chopper\tests\st0000_00_00.tex
E:\MHR\MHR_Tex_Chopper\tests\IBL.tex
E:\MHR\MHR_Tex_Chopper\tests\ibl00_skylight_00.tex
E:\MHR\MHR_Tex_Chopper\tests\World_custom.tex
E:\MHR\MHR_Tex_Chopper\tests\Snow_SkyGradation_Daytime.tex
E:\MHR\MHR_Tex_Chopper\tests\parts_NRRT.tex
E:\MHR\MHR_Tex_Chopper\tests\npc013_00_eye_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\em109_scale_NRRT.tex
E:\MHR\MHR_Tex_Chopper\tests\npc311_02_body_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\hand000_NRRT.tex
E:\MHR\MHR_Tex_Chopper\tests\npc001_00_katana_NRRT.tex
E:\MHR\MHR_Tex_Chopper\tests\em109_00_1_NRRT.tex
E:\MHR\MHR_Tex_Chopper\tests\emp005_00_NRRT.tex
E:\MHR\MHR_Tex_Chopper\tests\S_Axe087_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\em092_00_tuta_NRRT.tex
E:\MHR\MHR_Tex_Chopper\tests\m_face000_4set_NRRT.tex
E:\MHR\MHR_Tex_Chopper\tests\em095_00_mudgold_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\twinkle_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\item_addonicon_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\map_icon_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\arms_addonicon_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\postman_anim_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\TreasureNote_Number_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\pl_wep_icon_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_04_0040_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\evc2008_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\Dust_parts_02_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\AutoSaveAnim_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\quest_counter_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_uketuke03_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\cmn_icon_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\quest_hud_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\thumb_o_parts_front_ID_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\map_011_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\filter_2_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\m02_suna25_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\NullNormal.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_bukiya_moji_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_tubo00_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_nuno09_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_ita11_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_ringoameya02_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_05_0055_MSK4.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_zakkayakomono05_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_onigiriya02_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m03_ki069_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_zabuton01_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_zakkayakomono12_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_tetu01_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m04_moyou03_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_kusari01_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_yakisakana_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_zakkayatubo_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_09_0011_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_zakkayakomono13_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_01_1107_MSK4.tex
E:\MHR\MHR_Tex_Chopper\tests\m03_ki73_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m03_ki72_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_1001_MSK4.tex
E:\MHR\MHR_Tex_Chopper\tests\I_Gla053_NRRT.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_0100_MSK4.tex
E:\MHR\MHR_Tex_Chopper\tests\m01_mokuzai06_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\hm12_001_kyoryuhouKusari_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m22_nawa01_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_07_1100_MSK4.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_01_1112_MSK4.tex
E:\MHR\MHR_Tex_Chopper\tests\m22_mokuzai09_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\cm_fire_900_BM.tex
E:\MHR\MHR_Tex_Chopper\tests\m03_mizu64_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_2001_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_2002_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_06_0003_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_04_0012_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_04_0063_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_04_0062_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_0093_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_em094_10_0000_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_07_2000_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\item_116_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_06_0002_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_0059_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_0500_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_0012_ALPG.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_10_2000_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_kusari01_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_04_0056_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\gm031_005_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\I_Gla003_b_DEMI.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_em089_10_0000_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\quest_type_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\CopyRight_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_01_0109_ALPG.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_02_0107_ALPG.tex
E:\MHR\MHR_Tex_Chopper\tests\S_Axe087_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_03_0106_ALPG.tex
E:\MHR\MHR_Tex_Chopper\tests\hm12_001_kyoryuhouKusari_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\tex_0004_cm_07_0101_ALPG.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_ita13_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\v01_sakanaya06_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\Bg_base_texture02_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\m22_komono05_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\Staffroll_LogoEffects_IAM.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_iwa23_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tent_naibu14_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_kusa11_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_mi21_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tent_naibu40_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tent_naibu69_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_mi20_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_kusa00_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_kusa30_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_kusa13_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tent_naibu12_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tent_naibu35_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tent_naibu84_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_su01_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_mi22_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tent_naibu57_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_kusa32_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_tuzura02_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_064_00_Atlas_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_nensekitan00_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\TopCloud_m02_MSK4.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tori02_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tent_naibu65_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tent_naibu83_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_mushi05_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\com_tent_naibu57_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\pop_tuzura02_ALBD.tex
E:\MHR\MHR_Tex_Chopper\tests\TexSkyBall_base03_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_mizu01_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_uroko02_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m08a00-tent2_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_wara01_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_yougan08_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_kusa02_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_yougan07_NRMR.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_mizu04_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_eda16_ALBA.tex
E:\MHR\MHR_Tex_Chopper\tests\m05_iwa23_ALBA.tex""".split("\n")

oldTestCases = r"""E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_0050_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\ltc2.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_09_0003_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\weapon\ShortSword\S_Swd058\S_Swd058_HDR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\mesh_0004_cm_00_0013_Vnm_MSK3.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\mesh_0004_cm_00_0012_Vnm_MSK3.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\ColorCubeLinear.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_05_0001_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\MasterMaterial\Textures\TexSkyBall_base_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\charamake\textures\CharaMake05_ALB.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\BlueNoise16x16.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\player\mod\m\pl238\m_leg238_CMM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\BlueNoise.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\NullGray.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\NullATOS.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\enemy\em109\00\mod\em109_00_FVM_MSK3.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\enemy\em109\common\mod\scale\em109_scale_CMM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\effect\Noise3D_MSK4.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\enemy\em001\common\mod\spine\em001_spine_EMI.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\item\gm\gm029_000\mod\gm029_000_FX_EMI.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\enemy\em102\00\mod\em102_00_feather_FVM_MSK3.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\otomo\OtDog\mod\common\otd_tail\otd_tail004\otd_tail004_FVM_MSK3.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_08_0004_MSK3.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\weapon\SlashAxe\S_Axe082\S_Axe082_FVM_MSK3.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03a07_flowmap00_MSK2.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\NullBlack3D.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\NullWhite.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_2011_ALB.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_ita11_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\backup\other\old_tex\pixtest_ALPG.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_kakejiku04_ALB.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_08_0001_ALB.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_kasaya03_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_onigiriya02_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03_ki069_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_mi21_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_zabuton00_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_04_0010_ALB.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_tatara01_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m04\textures\m04_moyou03_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_mi20_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_kusari01_ALB.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_yakisakana_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_zakkayatubo_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_2010_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_onigiriya04_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_kusa13_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03_ki73_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03_ki72_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_zakkayakomono09_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\weapon\SlashAxe\S_Axe087\S_Axe087_CMM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_onigiriya01_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m01\textures\m01_mokuzai05_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tent_naibu12_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m22\textures\m22_nawa01_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_kusa32_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\Test\Light\tex\Light_test_ALB.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_kusa11_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\SpeedT_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\CAPCOM_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m02\textures\m02a00_kinkei2_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_miki04_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\cloud80_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_kiri01_ALB.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\player\mod\m\pl201\m_wst201_NRRT.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\player\mod\common_tex\eye_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_08_0001_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\player\mod\m\pl200\m_leg200_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\RE_ENGINE_LIBRARY\VFX_Library\Shader\SourceTexture\shader_waterfall_distrtion\shader_waterfall_distortion_loopmask_MSK1.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_mask03_MSK1.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_nuno09_MSK1.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\player\mod\f\hair\f_hair007\f_hair007_Accesories_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\VolumeNoise_LIN.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_kasaya04_MSK1.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_tyoutinmoji08_MSK1.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_nuno09_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m01\textures\m01_moyou06_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\effect\chijiiwa_pat128_MSK1.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_su03_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m04\textures\m04_moyou03_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_kusari01_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_nuno03_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\lens_mask.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_kasaya03_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_kusa13_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m01\textures\m01_kusa34_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_zakkayakomono09_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\weapon\SlashAxe\S_Axe085\S_Axe085_FX.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_mi22_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m01\textures\m01_eda09_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03_ki73_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03_ki41_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m22\textures\m22_sango04_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\Eyeball\eye_OCC.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m02\textures\m05_064_00_Atlas_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m02\textures\m02a00_kinkei2_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03_ki48_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_kusa06_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_kiri01_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_su_09_ALP.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_flow08_MSK2.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m01\textures\h01_mizu01_MSK2.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\enemy\ems092\common\mod\clew\ems092_clew_FX_EMI.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_a03_mizu01_flow_MSK2.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_flow02_MSK2.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_mizu01_flow_MSK2.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03_flow31_MSK2.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\NullBlackCubemap.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\NullLightmap.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\a04\other\CubeMap\CubeMap_a04_junbi.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\MasterMaterial\Textures\IBL_small.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\a05\other\CubeMap\cubemap_2.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\MaterialEditor\st0000\st0000_00_00.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\MasterMaterial\Textures\IBL.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\systems\rendering\MaterialEditor\st8000_01\ibl00_skylight_00.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\a04\World_custom.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\MasterMaterial\Textures\Snow_SkyGradation_Daytime.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\player\mod\common_tex\parts_NRRT.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\npc\mod\npc013_00\npc013_00_body\npc013_00_eye_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\enemy\em109\common\mod\scale\em109_scale_NRRT.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\npc\mod\npc311_00\npc311_00_body\npc311_02_body_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\player\mod\common_tex\hand\hand000_NRRT.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\npc\mod\npc001_00\npc001_00_body\npc001_00_katana_NRRT.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\enemy\em109\00\mod\em109_00_1_NRRT.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\enemy\pop\emp005\00\mod\emp005_00_NRRT.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\weapon\SlashAxe\S_Axe087\S_Axe087_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\enemy\em092\00\mod\em092_00_tuta_NRRT.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\player\mod\face\m_face000_4set_NRRT.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\enemy\em095\00\mod\HQ\em095_00_mudgold_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\twinkle_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\item_addonicon_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\map\map_icon_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\arms_addonicon_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\postman_anim_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\TreasureNote_Number_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\pl_wep_icon_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_04_0040_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\event\evc2008\evc2008_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\Dust_parts_02_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\AutoSaveAnim_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\quest_counter_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_uketuke03_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\cmn_icon_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\quest_hud_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\thumb_o_parts_front_ID_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\map\map_011_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\filter_2_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m02\textures\m02_suna25_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\backup\takechi\NullNormal.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_bukiya_moji_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_tubo00_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_nuno09_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_ita11_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_ringoameya02_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_05_0055_MSK4.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_zakkayakomono05_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_onigiriya02_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03_ki069_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_zabuton01_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_zakkayakomono12_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_tetu01_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m04\textures\m04_moyou03_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_kusari01_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_yakisakana_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_zakkayatubo_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_09_0011_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_zakkayakomono13_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_01_1107_MSK4.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03_ki73_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03_ki72_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_1001_MSK4.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\weapon\InsectGlaive\I_Gla053\I_Gla053_NRRT.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_0100_MSK4.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m01\textures\m01_mokuzai06_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\huntingMachine\textures\hm12_001_kyoryuhouKusari_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m22\textures\m22_nawa01_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_07_1100_MSK4.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_01_1112_MSK4.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m22\textures\m22_mokuzai09_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\backup\Takai\DDS\Ganma\cm_fire_900_BM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m03\textures\m03_mizu64_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_2001_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_2002_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_06_0003_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_04_0012_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_04_0063_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_04_0062_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_0093_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_em094_10_0000_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_07_2000_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\item\item\item_116\mod\item_116_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_06_0002_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_0059_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_0500_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_0012_ALPG.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_10_2000_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_kusari01_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_04_0056_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\item\gm\gm031_005\mod\gm031_005_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\weapon\InsectGlaive\I_Gla003\I_Gla003_b_DEMI.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_em089_10_0000_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\quest_type_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\Photo\CopyRight_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_01_0109_ALPG.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_02_0107_ALPG.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\weapon\SlashAxe\S_Axe087\S_Axe087_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_03_0106_ALPG.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\huntingMachine\textures\hm12_001_kyoryuhouKusari_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\vfx\mtu\tex_0004_cm_07_0101_ALPG.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_ita13_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\v01\textures\v01_sakanaya06_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\Bg_base_texture02_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m22\textures\m22_komono05_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\gui\80_Texture\Staffroll_LogoEffects_IAM.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_iwa23_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tent_naibu14_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_kusa11_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_mi21_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tent_naibu40_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tent_naibu69_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_mi20_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_kusa00_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_kusa30_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_kusa13_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tent_naibu12_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tent_naibu35_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tent_naibu84_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_su01_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_mi22_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tent_naibu57_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_kusa32_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_tuzura02_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m02\textures\m05_064_00_Atlas_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_nensekitan00_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\TopCloud_m02_MSK4.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tori02_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tent_naibu65_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tent_naibu83_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_mushi05_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\com_tent_naibu57_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\pop\textures\pop_tuzura02_ALBD.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\common\textures\TexSkyBall_base03_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_mizu01_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_uroko02_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m08a00-tent2_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_wara01_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_yougan08_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_kusa02_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_yougan07_NRMR.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_mizu04_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_eda16_ALBA.tex
E:\MHR\GameFiles\RETool\re_chunk_000\natives\NSW\stage\m05\textures\m05_iwa23_ALBA.tex""".split("\n")

# import shutil
# from pathlib import Path
# newfolder = Path(r"E:\MHR\MHR_Tex_Chopper\tests")
# for path in oldTestCases:
#     newPath = newfolder/(Path(path).stem+".tex")
#     shutil.copyfile(path,newPath)
#     print(newPath)